In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns = ['EIN', 'NAME'])

In [4]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE

applicationTypesReplace = list(counts[counts<500].index)
applicationTypesReplace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
# Replace in dataframe
for app in applicationTypesReplace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [10]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
countsClassificationValue = application_df['CLASSIFICATION'].value_counts()

In [11]:
# You may find it helpful to look at CLASSIFICATION value counts >1

countsclassification = countsClassificationValue[countsClassificationValue>1]
countsclassification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (countsClassificationValue[countsClassificationValue<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [13]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [17]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [18]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

array([1, 1, 0, ..., 0, 1, 0])

In [19]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()



## First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 350

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 477 (1.86 KB)
Trainable params: 477 (1.86 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [23]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 6s 6ms/step - loss: 0.6158 - accuracy: 0.6847 - val_loss: 0.5639 - val_accuracy: 0.7344
Epoch 2/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5674 - accuracy: 0.7217 - val_loss: 0.5551 - val_accuracy: 0.7344
Epoch 3/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5603 - accuracy: 0.7244 - val_loss: 0.5490 - val_accuracy: 0.7334
Epoch 4/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5574 - accuracy: 0.7255 - val_loss: 0.5477 - val_accuracy: 0.7339
Epoch 5/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5565 - accuracy: 0.7258 - val_loss: 0.5470 - val_accuracy: 0.7365
Epoch 6/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5553 - accuracy: 0.7252 - val_loss: 0.5451 - val_accuracy: 0.7365
Epoch 7/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5537 - accuracy: 0.7260 - val_loss: 0.5454 - val_accuracy: 0.7352
Epoch 8/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7273 - val_loss: 0.5465 - val_accuracy: 0.7341
Epoch 9/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5528 - accuracy: 0.7268 - val_loss: 0.5437 - val_accuracy: 0.7370
Epoch 10/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5522 - accuracy: 0.7272 - val_loss: 0.5445 - val_accuracy: 0.7354
Epoch 11/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5511 - accuracy: 0.7273 - val_loss: 0.5423 - val_accuracy: 0.7372
Epoch 12/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5506 - accuracy: 0.7284 - val_loss: 0.5429 - val_accuracy: 0.7378
Epoch 13/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5499 - accuracy: 0.7274 - val_loss: 0.5438 - val_accuracy: 0.7352
Epoch 14/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7267 - val_loss: 0.5441 - val_accuracy: 0.7367
Epoch 15/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5496 - accuracy: 0.7278 - val_loss: 0.5421 - val_accuracy: 0.7359
Epoch 16/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5497 - accuracy: 0.7277 - val_loss: 0.5439 - val_accuracy: 0.7380
Epoch 17/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5492 - accuracy: 0.7295 - val_loss: 0.5431 - val_accuracy: 0.7372
Epoch 18/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7277 - val_loss: 0.5415 - val_accuracy: 0.7359
Epoch 19/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5485 - accuracy: 0.7289 - val_loss: 0.5431 - val_accuracy: 0.7365
Epoch 20/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7278 - val_loss: 0.5448 - val_accuracy: 0.7367
Epoch 21/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5484 - accuracy: 0.7295 - val_loss: 0.5418 - val_accuracy: 0.7370
Epoch 22/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5481 - accuracy: 0.7288 - val_loss: 0.5422 - val_accuracy: 0.7367
Epoch 23/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5476 - accuracy: 0.7289 - val_loss: 0.5448 - val_accuracy: 0.7365
Epoch 24/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5482 - accuracy: 0.7294 - val_loss: 0.5428 - val_accuracy: 0.7352
Epoch 25/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5478 - accuracy: 0.7283 - val_loss: 0.5429 - val_accuracy: 0.7346
Epoch 26/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5477 - accuracy: 0.7287 - val_loss: 0.5422 - val_accuracy: 0.7372
Epoch 27/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7290 - val_loss: 0.5448 - val_accuracy: 0.7346
Epoch 28/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7292 - val_loss: 0.5441 - val_accuracy: 0.7370
Epoch 29/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7295 - val_loss: 0.5423 - val_accuracy: 0.7378
Epoch 30/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7301 - val_loss: 0.5422 - val_accuracy: 0.7375
Epoch 31/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5472 - accuracy: 0.7295 - val_loss: 0.5421 - val_accuracy: 0.7370
Epoch 32/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7297 - val_loss: 0.5431 - val_accuracy: 0.7352
Epoch 33/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7288 - val_loss: 0.5442 - val_accuracy: 0.7359
Epoch 34/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7287 - val_loss: 0.5420 - val_accuracy: 0.7375
Epoch 35/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5470 - accuracy: 0.7297 - val_loss: 0.5434 - val_accuracy: 0.7367
Epoch 36/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5464 - accuracy: 0.7301 - val_loss: 0.5433 - val_accuracy: 0.7385
Epoch 37/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7302 - val_loss: 0.5412 - val_accuracy: 0.7372
Epoch 38/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5469 - accuracy: 0.7299 - val_loss: 0.5422 - val_accuracy: 0.7380
Epoch 39/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7302 - val_loss: 0.5428 - val_accuracy: 0.7346
Epoch 40/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7303 - val_loss: 0.5426 - val_accuracy: 0.7349
Epoch 41/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7305 - val_loss: 0.5436 - val_accuracy: 0.7372
Epoch 42/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7285 - val_loss: 0.5424 - val_accuracy: 0.7357
Epoch 43/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5465 - accuracy: 0.7305 - val_loss: 0.5421 - val_accuracy: 0.7378
Epoch 44/100
684/684 [==============================] - 3s 5ms/step - loss: 0.5465 - accuracy: 0.7298 - val_loss: 0.5429 - val_accuracy: 0.7367
Epoch 45/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5466 - accuracy: 0.7299 - val_loss: 0.5432 - val_accuracy: 0.7357
Epoch 46/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5465 - accuracy: 0.7296 - val_loss: 0.5440 - val_accuracy: 0.7362
Epoch 47/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7305 - val_loss: 0.5430 - val_accuracy: 0.7359
Epoch 48/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7295 - val_loss: 0.5439 - val_accuracy: 0.7362
Epoch 49/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7296 - val_loss: 0.5423 - val_accuracy: 0.7359
Epoch 50/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7304 - val_loss: 0.5431 - val_accuracy: 0.7352
Epoch 51/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7306 - val_loss: 0.5434 - val_accuracy: 0.7354
Epoch 52/100
684/684 [==============================] - 2s 4ms/step - loss: 0.5460 - accuracy: 0.7315 - val_loss: 0.5434 - val_accuracy: 0.7357
Epoch 53/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7314 - val_loss: 0.5435 - val_accuracy: 0.7297
Epoch 54/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7306 - val_loss: 0.5459 - val_accuracy: 0.7328
Epoch 55/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7311 - val_loss: 0.5432 - val_accuracy: 0.7352
Epoch 56/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7315 - val_loss: 0.5431 - val_accuracy: 0.7346
Epoch 57/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7322 - val_loss: 0.5441 - val_accuracy: 0.7354
Epoch 58/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5458 - accuracy: 0.7310 - val_loss: 0.5451 - val_accuracy: 0.7352
Epoch 59/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5457 - accuracy: 0.7319 - val_loss: 0.5424 - val_accuracy: 0.7362
Epoch 60/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5457 - accuracy: 0.7318 - val_loss: 0.5434 - val_accuracy: 0.7380
Epoch 61/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7316 - val_loss: 0.5428 - val_accuracy: 0.7352
Epoch 62/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7337 - val_loss: 0.5433 - val_accuracy: 0.7300
Epoch 63/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7307 - val_loss: 0.5424 - val_accuracy: 0.7354
Epoch 64/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7316 - val_loss: 0.5432 - val_accuracy: 0.7336
Epoch 65/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7324 - val_loss: 0.5416 - val_accuracy: 0.7352
Epoch 66/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5453 - accuracy: 0.7318 - val_loss: 0.5428 - val_accuracy: 0.7352
Epoch 67/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7319 - val_loss: 0.5423 - val_accuracy: 0.7357
Epoch 68/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7319 - val_loss: 0.5449 - val_accuracy: 0.7354
Epoch 69/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7321 - val_loss: 0.5418 - val_accuracy: 0.7354
Epoch 70/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7308 - val_loss: 0.5425 - val_accuracy: 0.7357
Epoch 71/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7315 - val_loss: 0.5428 - val_accuracy: 0.7346
Epoch 72/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5451 - accuracy: 0.7323 - val_loss: 0.5439 - val_accuracy: 0.7354
Epoch 73/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7319 - val_loss: 0.5433 - val_accuracy: 0.7321
Epoch 74/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7327 - val_loss: 0.5420 - val_accuracy: 0.7367
Epoch 75/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5449 - accuracy: 0.7313 - val_loss: 0.5445 - val_accuracy: 0.7297
Epoch 76/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7313 - val_loss: 0.5426 - val_accuracy: 0.7365
Epoch 77/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7332 - val_loss: 0.5420 - val_accuracy: 0.7352
Epoch 78/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7327 - val_loss: 0.5435 - val_accuracy: 0.7315
Epoch 79/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5447 - accuracy: 0.7314 - val_loss: 0.5432 - val_accuracy: 0.7375
Epoch 80/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7317 - val_loss: 0.5429 - val_accuracy: 0.7362
Epoch 81/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7316 - val_loss: 0.5426 - val_accuracy: 0.7385
Epoch 82/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7325 - val_loss: 0.5427 - val_accuracy: 0.7315
Epoch 83/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7327 - val_loss: 0.5437 - val_accuracy: 0.7388
Epoch 84/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7321 - val_loss: 0.5427 - val_accuracy: 0.7367
Epoch 85/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7325 - val_loss: 0.5436 - val_accuracy: 0.7365
Epoch 86/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5445 - accuracy: 0.7321 - val_loss: 0.5431 - val_accuracy: 0.7393
Epoch 87/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5446 - accuracy: 0.7312 - val_loss: 0.5423 - val_accuracy: 0.7339
Epoch 88/100
684/684 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7319 - val_loss: 0.5431 - val_accuracy: 0.7344
Epoch 89/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5445 - accuracy: 0.7326 - val_loss: 0.5433 - val_accuracy: 0.7362
Epoch 90/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5440 - accuracy: 0.7319 - val_loss: 0.5458 - val_accuracy: 0.7359
Epoch 91/100
684/684 [==============================] - 9s 13ms/step - loss: 0.5445 - accuracy: 0.7317 - val_loss: 0.5434 - val_accuracy: 0.7352
Epoch 92/100
684/684 [==============================] - 4s 6ms/step - loss: 0.5443 - accuracy: 0.7324 - val_loss: 0.5431 - val_accuracy: 0.7385
Epoch 93/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5442 - accuracy: 0.7316 - val_loss: 0.5426 - val_accuracy: 0.7313
Epoch 94/100
684/684 [==============================] - 5s 7ms/step - loss: 0.5436 - accuracy: 0.7326 - val_loss: 0.5430 - val_accuracy: 0.7328
Epoch 95/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7325 - val_loss: 0.5427 - val_accuracy: 0.7339
Epoch 96/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7320 - val_loss: 0.5430 - val_accuracy: 0.7264
Epoch 97/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7325 - val_loss: 0.5432 - val_accuracy: 0.7315
Epoch 98/100
684/684 [==============================] - 2s 3ms/step - loss: 0.5438 - accuracy: 0.7313 - val_loss: 0.5447 - val_accuracy: 0.7349
Epoch 99/100
684/684 [==============================] - 3s 4ms/step - loss: 0.5436 - accuracy: 0.7327 - val_loss: 0.5437 - val_accuracy: 0.7305
Epoch 100/100
684/684 [==============================] - 5s 7ms/step - loss: 0.5439 - accuracy: 0.7322 - val_loss: 0.5427 - val_accuracy: 0.7326

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5535 - accuracy: 0.7252 - 373ms/epoch - 1ms/step
Loss: 0.553521454334259, Accuracy: 0.7252478003501892

In [25]:
# Export our model to HDF5 file
from google.colab import files

nn.save('/content/ModelB1.h5')
files.download('/content/ModelB1.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(